FROM mcr.microsoft.com/mmlspark/release

LABEL name="Container image with MML Spark and Jupyter"

WORKDIR /TextAnalysis

COPY ./online_retail.csv .

RUN pip3 install -U pip
RUN pip3 install -U jupyter
RUN pip3 install -U matplotlib
RUN pip3 install -U seaborn

# Add Tini. Tini operates as a process subreaper for jupyter. This prevents
# kernel crashes.
ENV TINI_VERSION v0.6.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT ["/usr/bin/tini", "--"]

EXPOSE 8888
CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0"]
